package core

const(
	RPC_ACTION_GET		= "GoLC.Get"
	RPC_ACTION_MGET		= "GoLC.MGet"
	RPC_ACTION_SET 		= "GoLC.Set"
	RPC_ACTION_DEL		= "GoLC.Del"
	RPC_ACTION_STATUS	= "GOLC.STATUS"
)

const (
	DEFALUT_CACHE_CONF_LIFEWINDOW = 3600;	//3600s
	DEFALUT_DBNAME	= "test"
)

const (
	SERVER_CONF_SECTION = "server"
	SERVER_NETWORK = "tcp"
	SERVER_ADDRESS = ":6078"
)

const (
	CLIENT_TIME_OUT = 5

)